#!/bin/bash
yum update -y
sudo yum install -y perl-Switch perl-DateTime perl-Sys-Syslog perl-LWP-Protocol-https perl-Digest-SHA.x86_64
cd /home/ec2-user/
# The command below will download the specified file from the S3 bucket
# File left as an example for security purposes.
#curl https://s3.amazonaws.com/examplefile.txt -O
